import {
  Globe,
  LayoutDashboard,
  Users,
  Server,
  Smartphone,
  Code2,
  Layers,
  ShieldCheck,
  Phone,
  RefreshCw,
  Clock,
  Mail,
  MapPin,
  Zap,
  Search,
  Plug,
  GitBranch,
  FileText,
  Calendar,
  Receipt,
  BarChart2,
  WifiOff,
  Bell,
  Camera,
  CreditCard,
  Repeat,
  Database,
  Cpu,
  Package,
  ShoppingCart,
  Factory,
  Wallet,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  globe: Globe,
  "layout-dashboard": LayoutDashboard,
  users: Users,
  server: Server,
  smartphone: Smartphone,
  "code-2": Code2,
  layers: Layers,
  "shield-check": ShieldCheck,
  phone: Phone,
  "refresh-cw": RefreshCw,
  clock: Clock,
  mail: Mail,
  "map-pin": MapPin,
  zap: Zap,
  search: Search,
  plug: Plug,
  "git-branch": GitBranch,
  "file-text": FileText,
  calendar: Calendar,
  receipt: Receipt,
  "bar-chart-2": BarChart2,
  "wifi-off": WifiOff,
  bell: Bell,
  camera: Camera,
  "credit-card": CreditCard,
  repeat: Repeat,
  database: Database,
  cpu: Cpu,
  package: Package,
  "shopping-cart": ShoppingCart,
  factory: Factory,
  wallet: Wallet,
};
